---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=g8swJODFCZOUCRY
    volumes:
      - ./config:/config
      - ~/:/home
    ports:
      - 1001:8443
    restart: unless-stopped
