services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1000:1000"
    ports:
      - 3000:3000
    restart: 'unless-stopped'
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.avilab.online # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
