---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: godofgeeks Homelab
description: Welcome to godofgeeks' homelab server
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
